import os
import argparse
from common import CONFIG
from common import IMPL_VERSION_INT
from common import SPEC_VERSION_INT
from common import write_if_changed

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output_header', type=str)
    args = parser.parse_args()
    return args


HEADER_GUARD = "VK_DOOB_DXGI_H"

INCLUDES = [
    "<vulkan/vulkan_core.h>",
    "<dxgi.h>"
]

DEFINES = {
    "VK_DOOB_dxgi_swapchain": 1,
    "VK_DOOB_DXGI_SWAPCHAIN_SPEC_VERSION": SPEC_VERSION_INT,
    "VK_DOOB_DXGI_SWAPCHAIN_EXTENSION_NAME": "\"VK_DOOB_dxgi_swapchain\"",
    "VK_LAYER_DOOB_DXGI_SWAPCHAIN_NAME": f"\"VK_LAYER_DOOB_dxgi_swapchain\"",
    "VK_LAYER_DOOB_DXGI_SWAPCHAIN_DESCRIPTION": f"\"{CONFIG['DESCRIPTION']}\"",

    "VK_LAYER_DOOB_API_VERSION_MAJOR": CONFIG['VERSION_MAJOR'],
    "VK_LAYER_DOOB_API_VERSION_MINOR": CONFIG['VERSION_MINOR'],
    "VK_LAYER_DOOB_API_VERSION_PATCH": CONFIG['VERSION_PATCH'],

    "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DXGI_PROPERTIES_DOOB": "((VkStructureType)(2123157880))",
    "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DXGI_FEATURES_DOOB": "((VkStructureType)(2123157881))",
    "VK_STRUCTURE_TYPE_DXGI_SWAPCHAIN_CREATE_INFO_DOOB": "((VkStructureType)(2123157882))"
}

FUNCTIONS = [
    {
        "name": "vkGetDxgiSwapchainHandleDOOB",
        "return": "VkResult",
        "parameters": [
            ("VkDevice", "device"),
            ("VkSwapchainKHR", "swapchain"),
            ("IDXGISwapChain**", "pDxgiSwapchain")
        ]
    }
]

ENUMS = [
    {
        "name": "VkDxgiDeviceVersionDOOB",
        "values": [
            ("VK_DXGI_DEVICE_VERSION_AUTO_DOOB", "0"),
            ("VK_DXGI_DEVICE_VERSION_D3D11_DOOB", "1"),
            ("VK_DXGI_DEVICE_VERSION_D3D12_DOOB", "2"),
            ("VK_DXGI_DEVICE_VERSION_MAX_ENUM_DOOB", "0x7FFFFFFF")
        ]
    }
]

STRUCTS = [
    {
        "name": "VkPhysicalDeviceDxgiPropertiesDOOB",
        "members": [
            ("VkStructureType", "sType"),
            ("const void*", "pNext"),
            ("VkBool32", "dxgiSwapchain")
        ]
    },
    {
        "name": "VkPhysicalDeviceDxgiFeaturesDOOB",
        "members": [
            ("VkStructureType", "sType"),
            ("const void*", "pNext"),
            ("VkBool32", "enableDxgiSwapchain"),
            ("VkDxgiDeviceVersionDOOB", "dxgiVersion")
        ]
    },
    {
        "name": "VkDxgiSwapchainCreateInfoDOOB",
        "members": [
            ("VkStructureType", "sType"),
            ("const void*", "pNext"),
            ("DXGI_SWAP_EFFECT", "swapEffect"),
            ("UINT", "flags") #Maybe replace with VkDxgiSwapchainCreateFlagsDOOB ?
        ]
    }
]

# --- 2. The Generator (Code Logic) ---

def generate_vk_header(path):
    lines = []
    
    lines.append("// GENERATED FILE - DO NOT EDIT MANUALLY")
    lines.append("// DevsOutOfBounds (2026 - 2026)")
    lines.append("// Generated by gen_headers.py")
    lines.append(f"#ifndef {HEADER_GUARD}")
    lines.append(f"#define {HEADER_GUARD}\n")
    for inc in INCLUDES:
        lines.append(f"#include {inc}")
    lines.append("")

    for name, val in DEFINES.items():
        lines.append(f"#define {name:<50} {val}")
    lines.append("")

    for enum in ENUMS:
        lines.append(f"enum {enum['name']} {{")
        for i, (name, val) in enumerate(enum['values']):
            sep = "," if i < len(enum['values']) - 1 else ""
            # Pretty print logic: Handle the MAX_ENUM spacing
            if "MAX_ENUM" in name:
                lines.append("")
            lines.append(f"    {name} = {val}{sep}")
        lines.append("};\n")

    for struct in STRUCTS:
        lines.append(f"typedef struct {struct['name']} {{")
        for type_name, var_name in struct['members']:
            lines.append(f"    {type_name:<35} {var_name};")
        lines.append(f"}} {struct['name']};\n")

    
    for function in FUNCTIONS:
        params_list = [f"{t} {n}" for t, n in function['parameters']]
        param_str = ", ".join(params_list)
        lines.append(f"typedef {function['return']} (VKAPI_PTR *PFN_{function['name']})({param_str});")

    lines.append(f"#endif // {HEADER_GUARD}")

    fullpath = os.path.abspath(path)
    write_if_changed(fullpath, "\n".join(lines))
    

if __name__ == "__main__":  
    args = get_args()
    generate_vk_header(args.output_header)
